name: stud_new
description: A Flutter app combining lecture streaming + document/audio features
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1  # use the latest since your Flutter is 3.27.2 with Dart 3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # From chacing (video app)
  video_player: ^2.8.6
  chewie: ^1.11.3

  # From both apps (take latest)
  shared_preferences: ^2.3.3

  # From abeja (pdf, audio, network, background work)
  http: ^1.2.2
  dio: ^5.7.0
  path_provider: ^2.0.15
  permission_handler: ^11.0.1
  flutter_pdfview: ^1.3.2
  just_audio: ^0.9.39
  audio_session: ^0.1.19
  connectivity_plus: ^6.1.1
  nearby_connections: ^4.3.0
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mock/

dependency_overrides:
  # Pin to Kotlin 1.9-compatible version to avoid Kotlin 2.2.0 artifacts on Android
  package_info_plus: ^8.0.2
  # Chewie pulls wakelock_plus; pin EXACTLY to a Kotlin 1.9-compatible version
  wakelock_plus: 1.3.1
